main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from .views import (
    # FBV:
    todo_list,
    todo_add,
    todo_update,
    todo_delete,
    # CBV:
    TodoListView,
    TodoCreateView,
    TodoDetailView,
    TodoUpdateView,
    TodoDeleteView,
)

# after '/':
urlpatterns = [
    # FBV:
    # path('list/', todo_list, name='todo_list'),
    # path('add/', todo_add, name='todo_add'),
    # path('update/<int:pk>', todo_update, name="todo_update"),
    # path('delete/<int:pk>', todo_delete, name="todo_delete"),
    # CBV:
    path('list/', TodoListView.as_view(), name='todo_list'),
    path('add/', TodoCreateView.as_view(), name='todo_add'),
    path('detail/<int:pk>', TodoDetailView.as_view(), name='todo_detail'),
    path('update/<int:pk>', TodoUpdateView.as_view(), name="todo_update"),
    path('delete/<int:pk>', TodoDeleteView.as_view(), name="todo_delete"),
]

todo/models.py
from django.db import models

status_choices = [
    ('C', 'Completed'),
    ('P', 'Pending'),
]

priority_choices = [
    (1, 'High'),
    (2, 'Medium'),
    (3, 'Low'),
]

class Todo(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    status = models.CharField(max_length=1, choices=status_choices, default='P')
    priority = models.SmallIntegerField(choices=priority_choices, default=2)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

todo/forms.py
from django import forms

from .models import (
    Todo
)

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        exclude = []

todo/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect

from .forms import (
    Todo, TodoForm
)

# ------------------------------------
# Function Based Views
# ------------------------------------

# List:
def todo_list(request):
    return render(request, 'list.html', {
        "todos": Todo.objects.all()
    })

# Add:
def todo_add(request):
    form = TodoForm(request.POST or None)
    if form.is_valid():
        form.save()
        # Message:
        messages.success(request, 'Kaydedildi.')
        # If OK redirect:
        return redirect('todo_list') # redirect('path_name')
    context = {
        "form": form
    }
    # return render(request, 'add.html', context)
    return render(request, 'add_update.html', context)

# Update:
def todo_update(request, pk):
    todo = Todo.objects.get(id=pk)
    form = TodoForm(instance=todo)
    if request.method== "POST":
        form = TodoForm(data=request.POST, instance=todo)
        if form.is_valid():
            form.save()
            messages.success(request, 'Güncellendi.')
            return redirect("todo_list")
    context = {
        'form': form,
        'todo': todo
    }
    # return render(request, 'update.html', context)
    return render(request, 'add_update.html', context)

# Delete:
def todo_delete(request, pk):
    todo = Todo.objects.get(id=pk)
    todo.delete()
    messages.success(request, 'Silindi.')
    # No need template.
    return redirect("todo_list")


# ------------------------------------
# Class Based Views
# ------------------------------------
from django.urls import reverse_lazy

from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)


class TodoListView(ListView):
    model = Todo
    ordering = ['-id']
    # template_name = 'todo_list.html' # after 'templates/' default: 'modelname/modelname_list.html'


class TodoDetailView(DetailView):
    model = Todo
    # template_name = 'todo_detail.html' # after 'templates/' default: 'modelname/modelname_detail.html'


class TodoCreateView(CreateView):
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo_list')
    # template_name = 'todo_form.html' # after 'templates/' default: 'modelname/modelname_form.html'

    def post(self, request, *args, **kwargs):
        messages.success(request, 'Kaydedildi.')
        return super().post(request, *args, **kwargs)


class TodoUpdateView(UpdateView):
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo_list')
    # template_name = 'todo_form.html' # after 'templates/' default: 'modelname/modelname_form.html'

    def post(self, request, *args, **kwargs):
        messages.success(request, 'Güncellendi.')
        return super().post(request, *args, **kwargs)


class TodoDeleteView(DeleteView):
    model = Todo
    # form_class = TodoForm
    success_url = reverse_lazy('todo_list')
    # template_name = 'todo_confirm_delete.html' # after 'templates/' default: 'modelname/modelname_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        messages.success(request, 'Silindi.')
        return super().post(request, *args, **kwargs)

todo/templates/add.html
{% extends 'base.html' %}

{% block container %}
<hr>
<h2>Add Todo</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Add Todo" />
</form>

{% endblock container %}

todo/templates/add_update.html
{% extends 'base.html' %}

{% block container %}
<hr>
<h2>Todo Add/Update</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Add/Update" />
</form>

{% endblock container %}

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style type="text/css">
        body {
            padding: 4%;
            color: #333;
            font-family: Tahoma, Verdana, Arial;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <h1>TODO APP</h1>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == "error" %}
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    
    {% block container %} {% endblock container %}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

todo/templates/list.html
{% extends 'base.html' %}

{% block container %}
<hr>
<h2>Todo List</h2>
<p><a href="/add" class="btn btn-primary">YENİ EKLE</a></p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>priority</th>
            <th>title</th>
            <th>created_date</th>
            <th>status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {# SingleLine Comment #}
    {% comment %}
        Multiline Comment
    {% endcomment %}
    {% for todo in todos %}
        <tr>
            <td>
                {% if todo.priority == 1 %}
                <b class="text-danger">{{ todo.get_priority_display }}</b>
                {% elif todo.priority == 2 %}
                <b class="text-warning">{{ todo.get_priority_display }}</b>
                {% else %}
                <b class="text-info">{{ todo.get_priority_display }}</b>
                {% endif %}
            </td>
            <td>{{ todo.title }}</td>
            <td>{{ todo.created_date }}</td>
            <td>
                {% if todo.status == "P" %}
                <b class="text-danger">{{ todo.get_status_display }}</b>
                {% else %}
                <b class="text-success">{{ todo.get_status_display }}</b>
                {% endif %}
            </td>
            <td>
                <a href="/update/{{ todo.id }}">Güncelle</a>
                <a href="/delete/{{ todo.id }}" onclick="return confirm('Are you sure?')">Sil</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock container %}

todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}
{% block container %}

<hr>
<h2>TodoDeleteView</h2>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" />
</form>

{% endblock container %}

todo/templates/todo/todo_detail.html
{% extends 'base.html' %}
{% block container %}

<hr>
<h2>TodoDetailView</h2>
<p><a href="/list" class="btn btn-primary">LIST</a></p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>priority</th>
            <th>title</th>
            <th>created_date</th>
            <th>status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                {% if todo.priority == 1 %}
                <b class="text-danger">{{ todo.get_priority_display }}</b>
                {% elif todo.priority == 2 %}
                <b class="text-warning">{{ todo.get_priority_display }}</b>
                {% else %}
                <b class="text-info">{{ todo.get_priority_display }}</b>
                {% endif %}
            </td>
            <td>{{ todo.title }}</td>
            <td>{{ todo.created_date }}</td>
            <td>
                {% if todo.status == "P" %}
                <b class="text-danger">{{ todo.get_status_display }}</b>
                {% else %}
                <b class="text-success">{{ todo.get_status_display }}</b>
                {% endif %}
            </td>
            <td>
                | <a href="/update/{{ todo.id }}">Güncelle</a>
                | <a href="/delete/{{ todo.id }}" onclick="return confirm('Are you sure?')">Sil</a>
            </td>
        </tr>
    </tbody>
</table>
<b>Açıklama:</b> <br> {{ todo.description }}
<hr>
<b>Kayıt:</b> <br> {{ todo.created_date }}
<b>Güncelleme:</b> <br> {{ todo.updated_date }}

{% endblock container %}

todo/templates/todo/todo_form.html
{% extends 'base.html' %}
{% block container %}

<hr>
<h2>TodoCreateView | TodoUpdateView</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Submit" />
</form>

{% endblock container %}

todo/templates/todo/todo_list.html
{% extends 'base.html' %}

{% block container %}
<hr>
<h2>Todo ListView</h2>
<p><a href="/add" class="btn btn-primary">YENİ EKLE</a></p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>priority</th>
            <th>title</th>
            <th>created_date</th>
            <th>status</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {# SingleLine Comment #}
    {% comment %}
        Multiline Comment
    {% endcomment %}
    {% for todo in object_list %}
        <tr>
            <td>
                {% if todo.priority == 1 %}
                <b class="text-danger">{{ todo.get_priority_display }}</b>
                {% elif todo.priority == 2 %}
                <b class="text-warning">{{ todo.get_priority_display }}</b>
                {% else %}
                <b class="text-info">{{ todo.get_priority_display }}</b>
                {% endif %}
            </td>
            <td><a href="/detail/{{ todo.id }}">{{ todo.title }}</a></td>
            <td>{{ todo.created_date }}</td>
            <td>
                {% if todo.status == "P" %}
                <b class="text-danger">{{ todo.get_status_display }}</b>
                {% else %}
                <b class="text-success">{{ todo.get_status_display }}</b>
                {% endif %}
            </td>
            <td>
                <a href="/update/{{ todo.id }}">Güncelle</a>
                <a href="/delete/{{ todo.id }}" onclick="return confirm('Are you sure?')">Sil</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock container %}

todo/templates/update.html
{% extends 'base.html' %}
{% block container %}

<hr>
<h2>{{ todo }}</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table>{{ form }}</table>
    <input type="submit" value="Add Todo" />
</form>

{% endblock container %}